version: "3.5"

services:
    app:
        build: .
        command: npm start
        ports:
            - "9002:9002"
        volumes:
            - .:/usr/app
        networks:
            - prod
        depends_on:
            - database

    database:
        image: mysql-container
        ports:
            - "3306:3036"
        environment:
            MYSQL_ROOT_PASSWORD: dbfaeterj
            MYSQL_DATABASE: dbfaeterjso2
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - db-volume:/var/lib/mysql
        networks:
            - prod

volumes:
    db-volume:

networks:
  prod:
    driver: bridge
    

